name: CI/CD - Strapi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t zayn63/strapi:latest .
          docker push zayn63/strapi:latest

      # Configure AWS
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Force ECS service to redeploy with the new image
      - name: Force ECS Deployment
        run: |
          aws ecs update-service \
            --cluster z-strapi-cluster \
            --service z-strapi-service \
            --force-new-deployment
